type Apartments {
  photo_url: String!
  is_super_host: Boolean
  name: String!
  rating: Int!
  apartment_type: String!
  location: String!
  beds: Int!
}

type Query {
  allApartments: [Apartments!]!
}
