fragment RoomFragment on Room {
  id
  name
  images
  apartmentType
  location
  beds
  bedrooms
  bathrooms
  guests
  price
  description
  cancellable
  hasTv
  hasKitchen
  hasAirconditioning
  hasWifi
  hasFreeParking
  createdAt
  updatedAt
}
